name: Build Minecraft Mod

on:
push:
branches: [ "main" ]
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Kodları çek
    uses: actions/checkout@v3

  - name: Java kur (JDK 17)
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: '17'

  - name: Gradle izin ver
    run: chmod +x gradlew

  - name: Modu build et
    run: ./gradlew build

  - name: Jar upload
    uses: actions/upload-artifact@v4
    with:
      name: chatgptmod
      path: build/libs/*.jar
```
